/**
 * Action de-duplication window preventing double-submit.
 * Ensures rapid triple-click yields single intent (server confirms once).
 * Correlation IDs tie toast pending/success/error for unified contract.
 *
 * Correlation IDs are generated by the canonical generator in
 * `correlationId.ts` so every call site emits one unified format.
 *
 * The dedup window MUST agree with the backend idempotency lock TTL so a
 * double-submit cannot slip past client dedup while the backend key is still
 * locked. The backend lock TTL is 30s; keep this in sync with it.
 */

import { generateCorrelationId } from './correlationId';

export interface DedupEntry {
  key: string;
  correlationId: string;
  idempotencyKey: string;
  timestamp: number;
}

/**
 * Backend idempotency lock TTL in milliseconds.
 * Must match the server-side lock TTL (30s) so client dedup and backend lock
 * agree — otherwise a double-submit after the client window but before the
 * backend lock expires would bypass client dedup.
 */
export const IDEMPOTENCY_LOCK_TTL_MS = 30_000;

const DEDUP_WINDOW_MS = IDEMPOTENCY_LOCK_TTL_MS;
const dedupMap = new Map<string, DedupEntry>();

export function getCorrelationId(): string {
  return generateCorrelationId();
}

export function shouldDedup(actionKey: string): { dedup: boolean; entry?: DedupEntry } {
  const existing = dedupMap.get(actionKey);
  if (existing && Date.now() - existing.timestamp < DEDUP_WINDOW_MS) {
    return { dedup: true, entry: existing };
  }
  return { dedup: false };
}

export function registerAction(actionKey: string, correlationId: string, idempotencyKey: string): DedupEntry {
  const entry: DedupEntry = { key: actionKey, correlationId, idempotencyKey, timestamp: Date.now() };
  dedupMap.set(actionKey, entry);
  // Auto-expire
  setTimeout(() => {
    const cur = dedupMap.get(actionKey);
    if (cur?.correlationId === correlationId) dedupMap.delete(actionKey);
  }, DEDUP_WINDOW_MS);
  return entry;
}

export function clearDedup(actionKey: string): void {
  dedupMap.delete(actionKey);
}

export function _clearAllForTests(): void {
  dedupMap.clear();
}

export const DEDUP_WINDOW = DEDUP_WINDOW_MS;
